### ISSUE TITLE
set .Values.image.tag to empty string (and let .Chart.AppVersion do that work)

### ISSUE THREAD

**Issue by wrenix** [opencloud-eu/helm#12]

**Comment by michaelstingl** [comment]
To add some context to this proposal for those unfamiliar with Helm best practices:

## Current Situation
In `values.yaml`, we currently have:
```yaml
image:
  repository: opencloudeu/opencloud-rolling
  tag: "2.1.0"  # <-- This is what should be empty
  pullPolicy: IfNotPresent
```

## Proposed Change
```yaml
image:
  repository: opencloudeu/opencloud-rolling
  tag: ""  # <-- Empty by default
  pullPolicy: IfNotPresent
```

## Why This Matters

1. **Chart.AppVersion is the source of truth**: In `Chart.yaml`, we define `appVersion: "2.1.0"` which represents the default version of the application that this chart installs.

2. **Template logic**: In the deployment templates, we should use:
   ```yaml
   image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
   ```
   This means: use the tag from values.yaml if specified, otherwise use Chart.AppVersion.

3. **Benefits**:
   - **Single source of truth**: Version is maintained in one place (Chart.yaml)
   - **Easier upgrades**: When releasing a new chart version, only Chart.yaml needs updating
   - **User overrides still work**: Users can still specify a custom tag in their values
   - **Follows Helm best practices**: This is the recommended pattern in the Helm community
   - **OCI Registry consistency**: When users install from `ghcr.io/opencloud-eu/helm-charts/opencloud:0.1.5`, they expect the chart to install the matching OpenCloud version by default

## Example Usage
```bash
# Uses the default version from Chart.AppVersion
helm install opencloud ./charts/opencloud
# or from OCI registry
helm install opencloud oci://ghcr.io/opencloud-eu/helm-charts/opencloud --version 0.1.5

# Override with a specific version
helm install opencloud ./charts/opencloud --set image.tag=2.2.0
# or from OCI registry
helm install opencloud oci://ghcr.io/opencloud-eu/helm-charts/opencloud --version 0.1.5 --set image.tag=2.2.0
```

This ensures that chart version and app version stay in sync, especially important when distributing via OCI registries.

**Note**: This improvement complements PR #49 (release governance) by making version management more consistent across the chart.

@wrenix is this what you had in mind?
