### ISSUE TITLE
Add a globals.image.registry and globals.image.pullPolicy

### ISSUE THREAD

**Issue by wrenix** [opencloud-eu/helm#38]
after registry split from repository, see #11.

it is nice to have a easy way to overwride all at once, if you have a mirror.

```yaml
global:
  image:
    # -- if set it will overwrite all registry entries
    registry:
    # -- if set it will overwrite all pullPolicy
    pullPolicy:

image:
  registry: docker.io
  repository: opencloudeu/opencloud-rolling
  pullPolicy: IfNotPresent
  tag: ""
collabora:
  image:
    registry: docker.io
    repository: collabora/code
    pullPolicy: IfNotPresent
    tag: "24.04.13.2.1"
``` 

here a nice and easy template snippet:
```
          {{- with .Values.image }}
          image: "{{ coalesce $.Values.global.image.registry .registry }}/{{ .repository }}:{{ .tag | default (printf "v%s" $.Chart.AppVersion) }}"
          imagePullPolicy: {{ coalesce $.Values.global.image.pullPolicy .pullPolicy }}
          {{- end }}
```
or even
```
          {{- with .Values.collabora.image }}
          image: "{{ coalesce $.Values.global.image.registry .registry }}/{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ coalesce $.Values.global.image.pullPolicy .pullPolicy }}
          {{- end }}
          env:
```
