### ISSUE TITLE
Option to configure other IDP

### ISSUE THREAD

**Issue by euh2** [opencloud-eu/helm#40]
In the charts Keycloak is included. But it would be nice to have the option to set another Open ID compatible IDP.

**Comment by michaelstingl** [comment]
Thanks for your feedback! The current Helm chart is tightly coupled with Keycloak as the identity provider, which limits flexibility for users who want to use other OIDC-compatible identity providers.

## Current Status

Currently, the Helm chart:
- Includes Keycloak as a built-in dependency
- Configures OpenCloud to connect specifically to this Keycloak instance
- Has hardcoded OIDC configuration values in the deployment.yaml
- Provides an option for basic auth (`opencloud.enableBasicAuth`) but it's tied to whether Keycloak is enabled

## Possible Solution

A more flexible approach would be:

1. Making Keycloak truly optional (not just a toggle between Keycloak and basic auth)
2. Adding support for configuring external OIDC providers
3. Restructuring the values.yaml to have a more generic IDP section

### Example Configuration Structure:

```yaml
# New IDP configuration structure
idp:
  # Type of identity provider to use: "keycloak", "oidc", "basic", or "none"
  type: "keycloak"
  
  # Keycloak-specific configuration (only used when type is "keycloak")
  keycloak:
    # Use internal or external Keycloak
    internal:
      enabled: true
      # existing Keycloak configuration...
    external:
      enabled: false
      # existing external Keycloak configuration...

  # Generic OIDC configuration (only used when type is "oidc")
  oidc:
    enabled: false
    issuer: "https://auth.example.com/realms/myrealm"
    clientId: "web"
    metadataUrl: "https://auth.example.com/realms/myrealm/.well-known/openid-configuration"
    scope: "openid profile email groups"
    # Claims mapping
    claims:
      user: "preferred_username"
      cs3: "username"
      role: "roles"

  # Basic auth configuration (only used when type is "basic")
  basic:
    enabled: false
    adminUser: "admin"
    adminPassword: "admin"
    createDemoUsers: false
```

## Alternative Approach

There's also a more modular approach demonstrated in this community guide: https://loku.be/250411-opencloud-on-kubernetes-locally-part-1

The author currently uses basic authentication:
```yaml
PROXY_ENABLE_BASIC_AUTH: "true"
ADMIN_PASSWORD: "admin"
```

While not offering a full alternative IDP implementation yet, this approach emphasizes flexibility by creating a custom umbrella chart that's less opinionated about which components to use. The author mentions potentially using Authentik or TinyAuth instead of Keycloak in the future.

**Comment by kastl-ars** [comment]
> Example Configuration Structure:

I really think this is useful, the only thing I find non-intuitive is to have an `enabled` switch in both the `internal` and the `external` keycloak section. If I set the `type` to `keycloak`, I either use the internal or the external one.

**Comment by hugoallaine** [comment]
I would like to add here the necessary steps I had to take to install OpenCloud using my Authentik instance. The research/testing and discussion history are available in detail in a thread on the Matrix server [here](https://matrix.to/#/!yspTqikkYDQwqWaana:matrix.org/$vaJgzNUFGM9f6mJ2CECc7khIio7TIaDhe95MJ0L6EYw?via=chat.opencloud.eu&via=matrix.org&via=allaine.cc)

First, on Authentik, you need to create an OAuth2/OpenID provider. Give it a name, select your preferred authorization flow (implicit or explicit), and then select Public. Copy the client ID generated by Authentik and paste it into values.yml in the variable [global.oidc.clientId](https://github.com/opencloud-eu/helm/blob/0e21105e7b3e2699f4f5dfa8226b3c25bfb577a7/charts/opencloud/values.yaml#L55). In Redirect URIs/Origins, add the following three entries: 
- https://cloud.mydomain.com
- https://cloud.mydomain.com/oidc-callback.html
- https://cloud.mydomain.com/oidc-silent-redirect.html 

(Type Strict)
Replace obviously "cloud.mydomain.com" by your OpenCloud URL. Confirm the creation of the Provider. 

Then you can either follow the steps described by @andibraeu or add the two variables in the section [opencloud.env](https://github.com/opencloud-eu/helm/blob/0e21105e7b3e2699f4f5dfa8226b3c25bfb577a7/charts/opencloud/values.yaml#L448). This does not require modifying the template (but you will get two warnings when running helm install, which you can ignore). It looks like this:

```
env:
  - name: WEB_OIDC_METADATA_URL
    value: <Your_Authentik_OpenID_Configuration_URL_of_the_opencloud_provider>
  - name: PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM
    value: groups
```

After that, make sure that in values.yml, the variable [global.oidc.issuer](https://github.com/opencloud-eu/helm/blob/0e21105e7b3e2699f4f5dfa8226b3c25bfb577a7/charts/opencloud/values.yaml#L53) is an exact copy and paste of the OpenID Configuration Issuer URL of the Provider created on Authentik (eg. `https://authentik.mydomain.com/application/o/opencloud/`). Next, check that [global.domain.keycloak](https://github.com/opencloud-eu/helm/blob/0e21105e7b3e2699f4f5dfa8226b3c25bfb577a7/charts/opencloud/values.yaml#L30) is equal to the subdomain used by your Authentik instance (eg. `authentik.mydomain.com`).

I had a problem with the token renewal in the background, which disconnected me from OpenCloud every 5 minutes and sent me back to the Authentik logout page. To fix this problem, I had to add a line to the csp.yaml.gotmpl file in the list [frame-src](https://github.com/opencloud-eu/helm/blob/0e21105e7b3e2699f4f5dfa8226b3c25bfb577a7/charts/opencloud/files/opencloud/csp.yaml.gotmpl#L17):
`- 'https://{{ .Values.global.domain.keycloak  }}/'`

This seems more like a bug than an adaptation issue for Authentik, and I wonder how it can work with Keycloak, which must use the same system. However, I admit that I don't know how Keycloak works with OpenCloud, so if anyone can enlighten me, I'd be grateful.

Finally, to permanently resolve the disconnection issue, you need to add a header to the Authentik rules of your reverse proxy, as shown in [this discussion](https://github.com/goauthentik/authentik/issues/5762#issuecomment-2545782324). This header allows your OpenCloud instance to make requests to Authentik in frame mode, which is not allowed by default. If, like me, you use Traefik, you simply need to create middleware like this:

```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware-csp-authentik-opencloud
  namespace: traefik
spec:
  headers:
    customResponseHeaders:
      Content-Security-Policy: "frame-ancestors 'self' https://cloud.mydomain.com"
```

Apply it with kubectl apply. Then add it to the *Authentik* ingress by adding the annotation:

```
annotations:
  traefik.ingress.kubernetes.io/router.middlewares: traefik-middleware-csp-authentik-opencloud@kubernetescrd
```

All is done. Your instance is ready!

I should point out that this method works perfectly for the web application but does not work for the phone application because there is another clientId and other hardcoded redirect URLs in the documentation, and therefore does not work with a single Authentik Provider to my knowledge. If you know how to do this properly, I'd like to hear from you.
