### ISSUE TITLE
Feature Reqeust: Inject sensitive values as secret

### ISSUE THREAD

**Issue by Tim-herbie** [opencloud-eu/helm#51]
Currently, almost all secrets are injected into the applications in plain text. This practice should be avoided in a production environment.

**Comment by suse-coder** [comment]
I use flux (flux-aio) with timoni flux-helm-release module. Best would be to have autogenerated Secret, that can be overridden by values reference.

**Comment by Tim-herbie** [comment]
@michaelstingl Wow, that’s an amazing requirement check with really insightful suggestions!

**What’s my target deployment scenario?**  
Currently, I’m evaluating OpenCloud for private use in my "homelab," which is configured with 100% high availability. However, for production scenarios, I would recommend opting for the Enterprise version.

**Do you have preferences for secret management approaches?**  
Yes, I definitely prefer native Kubernetes Secrets, as you mentioned—they integrate well with any external secret provider.

**Basic Structure**  
I would choose option 1) and option 3):  
- Option 1: Absolutely yes!  
- Option 2: I don’t see a real need for this parameter.  
- Option 3: Perfect for development and starting out with the Helm chart, also great for setting default values.

I see no reason not to create secrets for each application, regardless of whether values are passed inline or sourced from existing secrets. I would prefer to have secret parameters defined per application, rather than using one big shared secret section.

```yml
# values.yaml
postgres:
  # default for testing purposes
  username: "postgres"
  password: "mysecretpassword"
  
  # option to use an existing secret for username and password
  # if set, the values above will be ignored
  # doc: It should contain keys 'username' and 'password'
  existingsecret: ""

keycloak:
  adminUser: admin
  adminPassword: admin

  # doc: It should contain keys 'username' and 'password'
  existingsecret: ""
...
```

Addtionally it´s conceivable to pretend the key´s of the secrets or to add a parameter like `secretKeyName` to let´s define the key dynamically through from the user.

**In Deployments**
```yml
env:
- name: POSTGRES_USER
  valueFrom:
    secretKeyRef:
      name: {{- if .Values.postgres.existingsecret }}
               {{ .Values.postgres.existingsecret }}
             {{- else }}
               example-postgres-secret
             {{- end }}
      key: username

- name: POSTGRES_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{- if .Values.postgres.existingsecret }}
               {{ .Values.postgres.existingsecret }}
             {{- else }}
               example-postgres-secret
             {{- end }}
      key: password

```

Example for secret creation:
```yml
{{- if not .Values.postgres.existingsecret }}
apiVersion: v1
kind: Secret
metadata:
  name: example-postgres-secret
type: Opaque
stringData:
  username: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
{{- end }}
```

**Testing**
Yes, I would love to test and validate the option using secrets. I am currently using HashiCorp Vault as my secret management tool and could run tests with it. However, I’m a bit busy at the moment, so it might take a few days before I can complete the testing.

If the feature is not under time pressure, I could imagine creating a PR.
