### ISSUE TITLE
[opencloud]: README.md includes detailed instructions for a Gateway, but the chart could generate it automatically?

### ISSUE THREAD

**Issue by kastl-ars** [opencloud-eu/helm#58]
Dear maintainers,

the opencloud chart's README.md includes a very long listing for a Gateway when using Cilium.

https://github.com/opencloud-eu/helm/blob/main/charts/opencloud/README.md?plain=1#L484

Same for the README.md in the repository root.
https://github.com/opencloud-eu/helm/blob/main/README.md?plain=1#L598

Fun thing is, the chart is able to automatically generate the gateway automatically. Or, almost.

```
# =====================================================================
# GATEWAY-API HTTPRoute
# =====================================================================
   
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # Enable HTTPRoute resources (set to true to create Gateway API routes)
  enabled: false
   
  # Gateway configuration
  gateway:
    # Create the gateway
    create: false
    # HTTPS Port to listen to (k3s traefik defaults to 8443)
    port: 443
    # Gateway name
    name: opencloud-gateway
    # Gateway class (defaults to "cilium")
    className: cilium
    # Gateway namespace (defaults to Release.Namespace)
    namespace: ""
    # Gateway annotations
    annotations:
```

I have not tested this, but one can supply custom annotations, so the whole gateway could be autogenerated, which would a) make the user's life easier and b) make the README.md shorter and easier to read.

Kind Regards,
Johannes
