### ISSUE TITLE
Setting global.tls.enabled only respected in ingress resources, not in gatewayAPI ressources

### ISSUE THREAD

**Issue by kastl-ars** [opencloud-eu/helm#60]
Dear maintainers,

the `global.tls.enabled` setting is used in the ingress resources as intended, e.g.

```yaml
  {{- if .Values.global.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.domain.opencloud | quote }}
      secretName: {{ .Values.global.tls.secretName }}
  {{- end }}
```

https://github.com/opencloud-eu/helm/blob/9e74a101ff1bf04acfcffc1a93ef98896f124428/charts/opencloud/templates/opencloud/ingress.yaml#L12

However, when using the gatewayAPI, this setting is ignored and TLS is always enabled.

e.g.

https://github.com/opencloud-eu/helm/blob/main/charts/opencloud/templates/gateway/gateway.yaml#L21

Is there a technical reason for this?

If so, it should be documented in the README.md that this setting is only used in ingress resources.

If there is no technical reason (I am not aware of any), then the missing if-statements should be added to allow the user to properly enable or disable TLS.

Kind Regards,
Johannes
