### ISSUE TITLE
Standardize internal/external structure across all services

### ISSUE THREAD

**Issue by michaelstingl** [opencloud-eu/helm#64]
## Current Inconsistency

The chart currently has inconsistent structure for internal/external service configuration:

### OpenCloud S3 Storage (well-structured ✅)
```yaml
opencloud:
  storage:
    s3:
      internal:
        enabled: true
        rootUser: opencloud
        rootPassword: opencloud-secret-key
        # ... all internal config nested here
      external:
        enabled: false
        endpoint: ""
        accessKey: ""
        # ... all external config nested here
```

### Keycloak (mixed structure ❌)
```yaml
keycloak:
  enabled: true  # <-- Should this be under internal?
  replicas: 1    # <-- Mixed with internal config
  adminUser: admin
  adminPassword: admin
  internal:
    enabled: true  # <-- Redundant with keycloak.enabled?
  external:
    enabled: false
    url: ""
    # ... external config
```

## Proposed Solution

Standardize all services to follow the same pattern:

```yaml
serviceName:
  internal:
    enabled: true
    # ALL internal configuration goes here
    replicas: 1
    adminUser: admin
    adminPassword: admin
    resources: {}
    persistence: {}
  external:
    enabled: false
    # ALL external configuration goes here
    url: ""
    adminUser: ""
    adminPassword: ""
```

## Benefits

1. **Consistency**: Same structure across all services
2. **Clarity**: Clear separation between internal and external configs
3. **Simplicity**: No confusion about where to place configuration
4. **Validation**: Easier to validate that only one mode is enabled

## Implementation Notes

- Since we're still in 0.x.x (pre-1.0), breaking changes are acceptable per semver
- Should be implemented across all services: keycloak, postgres, minio, etc.
- Update Chart version to 0.2.0 to signal breaking changes

## Related

- Identified in PR #63 by @Tim-herbie
