### ISSUE TITLE
Standardize credential naming conventions (username/password)

### ISSUE THREAD

**Issue by michaelstingl** [opencloud-eu/helm#65]
## Current Inconsistency

The chart uses different naming patterns for credentials across services:

### Username fields
- `keycloak.adminUser`
- `postgres.user`
- `opencloud.storage.s3.internal.rootUser`
- `rabbitmq.username`
- Some services use `username` (with 'name')

### Password fields
- `keycloak.adminPassword`
- `postgres.password`
- `opencloud.adminPassword`
- `opencloud.storage.s3.internal.rootPassword`
- Various other patterns

### Database-specific
- `postgres.database`
- `onlyoffice.database.name`
- Different patterns for database names

## Problems

1. **Confusion**: Users need to remember different field names for each service
2. **Error-prone**: Easy to use wrong field name
3. **Inconsistent with upstream charts**: Some naming comes from upstream conventions
4. **Documentation complexity**: Need to document each variation

## Proposed Solution

Standardize on consistent naming:

```yaml
# Option 1: Always use 'username' and 'password'
service:
  username: admin
  password: secret
  database:
    name: mydb
    username: dbuser
    password: dbpass

# Option 2: Always use 'user' and 'password'  
service:
  user: admin
  password: secret
  database:
    name: mydb
    user: dbuser
    password: dbpass
```

## Recommendation

Use **Option 1** (`username`/`password`) because:
- More explicit and clear
- Aligns with Kubernetes Secret conventions
- Used by many popular Helm charts

## Implementation Notes

- Since we're in 0.x.x, breaking changes are acceptable per semver
- Update all services to use consistent naming
- Update documentation accordingly

## Related

- Identified in PR #63 by @Tim-herbie
