### ISSUE TITLE
Inconsistent rendering of OC_INSECURE and PROXY_ENABLE_BASIC_AUTH?

### ISSUE THREAD

**Issue by kastl-ars** [opencloud-eu/helm#68]
Dear maintainers,

I just noticed that both `opencloud.insecure` and `opencloud.enableBasicAuth` are set as booleans according to the `values.yaml` and the README.md.

But they are rendered differently in the template:

```
            - name: OC_INSECURE
              value: "{{ .Values.opencloud.insecure }}"
            # Basic auth (only needed when not using Keycloak)
            - name: PROXY_ENABLE_BASIC_AUTH
              value: {{ tpl (toString .Values.opencloud.enableBasicAuth) . | quote }}
```

The first way of just using the value in quotes looks easier.
The second way looks more reliable, i.e. if someone uses a string `"true"` instead of a boolean, this might also do the right thing.

I have not checked whether there are other Booleans where the rendering might be inconsistent.

Kind Regards,
Johannes

**Comment by michaelstingl** [comment]
Thank you for catching this inconsistency! You're absolutely right - boolean values are rendered differently throughout the templates.

## Current Situation

```yaml
# Simple approach (might break with non-boolean values)
- name: OC_INSECURE
  value: "{{ .Values.opencloud.insecure }}"

# Safer approach (handles edge cases)
- name: PROXY_ENABLE_BASIC_AUTH
  value: {{ tpl (toString .Values.opencloud.enableBasicAuth) . | quote }}
```

## Other Examples Found

Looking at the deployment template, I found more inconsistencies:
- `opencloud.smtp.insecure` uses the simple approach (line 195)
- Most boolean values use the simple approach
- Only `PROXY_ENABLE_BASIC_AUTH` uses the complex approach

## Analysis

The complex approach with `toString` and `quote` is more robust because:
1. Handles cases where users might set `"true"` (string) instead of `true` (boolean)
2. Ensures proper quoting for the environment variable
3. Prevents template rendering errors

## Recommendation

All boolean environment variables should use the same approach. The safer pattern would be:
```yaml
value: {{ .Values.someBoolean | toString | quote }}
```

This is a good candidate for standardization. Would you like to create a PR to fix this inconsistency?
