### ISSUE TITLE
Using existing charts for minio, collabora ... as subchart

### ISSUE THREAD

**Issue by wrenix** [opencloud-eu/helm#7]
We should not implement everything new.

here are the official supported charts:
  - [minio](https://github.com/minio/minio/tree/master/helm/minio)
  - [collabora](https://github.com/CollaboraOnline/online/tree/master/kubernetes/helm/collabora-online)

**Comment by butonic** [comment]
I just tried to change to the official chart instead of https://github.com/opencloud-eu/helm/pull/26. Configuring the collabora-online chart correctly requires setting various domains for CORS, aliasgroups and frame_ancestors. We cannot use template values in the values.yaml and I would actually prefer using something like helmfile to template the different charts, eg:
```
# values.gotmpl
collabora:
  aliasgroups:
    - host: "http://opencloud-collaboration:9300"
      aliases:
        - "https://{{ .Values.global.domain.wopi }}"

```

having to write the same string over and over is very error prone ...
