### ISSUE TITLE
Gateway name mismatch in documentation after PR #16

### ISSUE THREAD

**Issue by michaelstingl** [opencloud-eu/helm#72]
## Description

In the Gateway API setup guide in `charts/opencloud/README.md`, there is a mismatch between the Gateway name created and the name referenced during installation:

- **Step 4** (line 494): Creates a Gateway named `cilium-gateway`
- **Step 6** (line 636): References `--set httpRoute.gateway.name=opencloud-gateway`

This causes the HTTPRoutes to fail because they're looking for a Gateway that doesn't exist with that name.

## Root cause

This inconsistency was introduced after PR #16 which made the Gateway API support generic and changed the expected gateway name from `cilium-gateway` to `opencloud-gateway`. However, the documentation in Step 4 was not updated to reflect this change.

## Expected behavior

The Gateway name should be consistent throughout the documentation.

## Suggested fix

In `charts/opencloud/README.md`, change the Gateway name in Step 4 from `cilium-gateway` to `opencloud-gateway` to match what the Helm chart expects:

```yaml
# gateway.yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: opencloud-gateway  # <- Change this
  namespace: kube-system
```

## Additional context

- Related to PR #16 which made Gateway API support generic
- Discovered while reviewing PR #66
- Note: After PR #61 is merged, this documentation will only exist in the chart-specific README
