### ISSUE TITLE
Add external PostgreSQL password support for OnlyOffice

### ISSUE THREAD

**Issue by michaelstingl** [opencloud-eu/helm#74]
## Description

OnlyOffice deployment doesn't support external PostgreSQL with password authentication. The `DB_PWD` or `DB_PASSWORD` environment variable is missing from the deployment template.

## Current Behavior

The OnlyOffice deployment only sets:
- `DB_TYPE`
- `DB_HOST`
- `DB_PORT`
- `DB_NAME`
- `DB_USER`

But no password field, causing authentication failures when using external PostgreSQL.

## Expected Behavior

Support external PostgreSQL with password authentication by:
1. Adding `DB_PWD` environment variable
2. Supporting both inline password and `existingSecret` configuration
3. Following the pattern used for other services in the chart

## Use Cases

- Managed database services (AWS RDS, Google Cloud SQL, Azure Database)
- Shared PostgreSQL clusters
- Corporate database infrastructure
- Compliance requirements for centralized database management

## Proposed Implementation

Add to `values.yaml`:
```yaml
onlyoffice:
  externalDatabase:
    enabled: false
    existingSecret: ""
    passwordKey: "password"
    password: ""
```

Add to deployment template:
```yaml
- name: DB_PWD
  valueFrom:
    secretKeyRef:
      name: {{ if .Values.onlyoffice.externalDatabase.existingSecret }}...
```

## Related Issues

- Reported in #71 by @mcfly-0908
- Related to PR #63 (general secret support)
