### ISSUE TITLE
Avoid setting defaults in the actual templates, use defaults in `values.yaml`

### ISSUE THREAD

**Issue by kastl-ars** [opencloud-eu/helm#78]
Dear maintainers,

as a user, it is annoying and error prone to have to search in two places for the default values used by a chart.

Therefore it would be better IMHO to avoid using ` ... | default 443` or similar in the actual templates and instead add those values to the `values.yaml`.

Yes, this makes the `values.yaml` larger, but at least everything is in one place.

Additionally, the chart uses defaults in the templates while those are also defined in the `values.yaml`.

Example:
```yaml
    - name: onlyoffice-https                                                                                                  
      protocol: HTTPS                                                                                                         
      port: {{ .Values.httpRoute.gateway.port | default 443 }}
```

```yaml
# =====================================================================
# GATEWAY-API HTTPRoute
# =====================================================================

# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # Enable HTTPRoute resources (set to true to create Gateway API routes)
  enabled: false

  # Gateway configuration
  gateway:
    # Create the gateway
    create: false
    # HTTPS Port to listen to (k3s traefik defaults to 8443)
    port: 443
```

Kind Regards,
Johannes
