### ISSUE TITLE
Convert PostgreSQL from Deployment to StatefulSet

### ISSUE THREAD

**Issue by michaelstingl** [opencloud-eu/helm#93]
## Problem Description

The PostgreSQL deployment in the OpenCloud Helm chart currently uses a `Deployment` resource with `strategy: Recreate`. While this works for basic use cases, it doesn't follow Kubernetes best practices for stateful workloads like databases.

### Current Issues:

1. **Pod Identity**: Deployments don't guarantee stable network identities for pods
2. **Storage**: While PVCs are retained, the pod-to-volume binding isn't as robust as with StatefulSets
3. **Scaling**: Future scaling scenarios (read replicas, HA) would be difficult with Deployments
4. **Recovery**: Pod rescheduling can be problematic with Deployments for stateful workloads

### Current Implementation:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencloud.postgres.fullname" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate  # Workaround for single-instance stateful behavior
```

## Proposed Solution

Convert the PostgreSQL deployment to use a StatefulSet, which provides:
- Stable, unique network identifiers
- Stable, persistent storage
- Ordered, graceful deployment and scaling
- Ordered, automated rolling updates

### Implementation Details:

1. **Change resource type from Deployment to StatefulSet**

2. **Add serviceName field** (required for StatefulSets):
```yaml
spec:
  serviceName: {{ include "opencloud.postgres.fullname" . }}
```

3. **Remove strategy block** (StatefulSets use different update strategies):
```yaml
# Remove:
# strategy:
#   type: Recreate
```

4. **Convert volume management to volumeClaimTemplates**:

Instead of:
```yaml
volumes:
  - name: data
    {{- if .Values.postgres.persistence.enabled }}
    persistentVolumeClaim:
      claimName: {{ include "opencloud.postgres.fullname" . }}-data
    {{- else }}
    emptyDir: {}
    {{- end }}
```

Use:
```yaml
{{- if .Values.postgres.persistence.enabled }}
volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.postgres.persistence.size }}
      {{- if .Values.postgres.persistence.storageClass }}
      storageClassName: {{ .Values.postgres.persistence.storageClass }}
      {{- end }}
{{- end }}
```

5. **Handle non-persistent case** in container volumeMounts:
```yaml
volumeMounts:
  - name: data
    mountPath: /var/lib/postgresql/data
    {{- if not .Values.postgres.persistence.enabled }}
    # For non-persistent mode, we need to add an emptyDir volume
    {{- end }}
```

6. **Add emptyDir for non-persistent mode**:
```yaml
{{- if not .Values.postgres.persistence.enabled }}
volumes:
  - name: data
    emptyDir: {}
{{- end }}
```

7. **Update the PVC template** (remove separate PVC creation):
   - Delete `charts/opencloud/templates/postgres/pvc.yaml`
   - StatefulSets manage PVCs automatically via volumeClaimTemplates

8. **Add podManagementPolicy** (optional, for flexibility):
```yaml
podManagementPolicy: Parallel  # or OrderedReady (default)
```

### ⚠️ Breaking Change
This is a **breaking change** for existing deployments. Users will need to:

1. **Backup data** before upgrading
2. **Delete the existing Deployment** (data in PVC is preserved)
3. **Apply the new StatefulSet** (it will reuse the existing PVC if names match)

### Migration Steps for Users:

```bash
# 1. Backup PostgreSQL data
kubectl exec -n opencloud deployment/opencloud-postgres -- \
  pg_dumpall -U keycloak > postgres-backup.sql

# 2. Scale down OpenCloud to prevent data writes
kubectl scale deployment opencloud -n opencloud --replicas=0

# 3. Delete the PostgreSQL deployment (PVC remains)
kubectl delete deployment opencloud-postgres -n opencloud

# 4. Upgrade the Helm chart
helm upgrade opencloud ./charts/opencloud -n opencloud

# 5. Verify PostgreSQL is running as StatefulSet
kubectl get statefulset -n opencloud
```

## Benefits

1. **Better resilience**: StatefulSets handle pod failures more gracefully
2. **Future-ready**: Easier to implement PostgreSQL replication/HA later
3. **Kubernetes-native**: Follows best practices for stateful workloads
4. **Stable network identity**: `postgres-0` instead of random pod names
5. **Ordered operations**: Proper shutdown/startup sequences

## Testing Requirements

1. **Fresh install**: Verify PostgreSQL starts correctly as StatefulSet
2. **Data persistence**: Verify data survives pod deletion/recreation
3. **Upgrade path**: Test migration from Deployment to StatefulSet
4. **Rollback**: Document rollback procedure if needed
5. **Non-persistent mode**: Test with `persistence.enabled: false`

## References

- Discussed in PR #63: https://github.com/opencloud-eu/helm/pull/63#issuecomment-2945680815
- Kubernetes StatefulSet documentation: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
- PostgreSQL on Kubernetes best practices: https://cloud.google.com/architecture/best-practices-for-postgresql-on-gke

### Future Enhancements (not in scope for this issue):
- Add init containers for database initialization
- Support for multiple databases/users (Issue #74)
- PostgreSQL replication support
- Backup/restore operators integration

### Chart Version
This change warrants a minor version bump (e.g., 0.3.0) due to the breaking change.
