### ISSUE TITLE
Implement multi-database PostgreSQL architecture

### ISSUE THREAD

**Issue by michaelstingl** [opencloud-eu/helm#94]
## Problem Description

The current PostgreSQL setup in the OpenCloud Helm chart only supports a single database and user, which limits scalability for services requiring external PostgreSQL. While this works for the current setup (Keycloak uses external PostgreSQL, OnlyOffice uses its built-in PostgreSQL), it prevents proper multi-service database architecture.

### Current Limitations:

1. **Single Database**: Only `keycloak` database is created
2. **Single User**: Only one PostgreSQL user (`keycloak`) 
3. **No Provisioning**: No mechanism to create additional databases/users
4. **Manual Configuration**: Adding new services requires manual database setup

### Current State:
- **Keycloak**: Uses external PostgreSQL from Helm chart
- **OnlyOffice**: Uses built-in PostgreSQL in its container (discovered in PR #63)
- **Future Services**: Would need manual database creation

## Proposed Solution

Implement a flexible multi-database PostgreSQL setup that supports:

1. **Multiple Databases**: Automatic creation of databases per service
2. **Multiple Users**: Dedicated users with proper permissions
3. **Init Configuration**: Database provisioning via ConfigMap/Job
4. **Service Isolation**: Each service gets its own database and credentials

#### Option 1: Init Container with Scripts
```yaml
postgres:
  databases:
    - name: keycloak
      user: keycloak
      password: keycloak  # or existingSecret
    - name: onlyoffice  
      user: onlyoffice
      password: onlyoffice  # or existingSecret
    - name: myservice
      user: myservice
      password: myservice  # or existingSecret
```

Use an init container that runs SQL scripts to create databases and users.

#### Option 2: PostgreSQL Operator
Consider using a PostgreSQL operator (like Zalando's postgres-operator) that handles:
- Database provisioning
- User management  
- Backup/restore
- High availability

#### Option 3: Job-based Provisioning
Create Kubernetes Jobs that run after PostgreSQL starts to provision databases.

### Recommended Approach:

Start with Option 1 (init container) as it's:
- Simple to implement
- No external dependencies
- Easy to understand and maintain
- Can be enhanced later

### Example Implementation:

1. **Update values.yaml**:
```yaml
postgres:
  # ... existing config ...
  
  # Multi-database configuration
  databases:
    keycloak:
      enabled: true
      database: keycloak
      username: keycloak
      existingSecret: ""  # or reference to secret
      # password: keycloak  # only if no existingSecret
    
    # Example for future services
    # onlyoffice:
    #   enabled: false
    #   database: onlyoffice
    #   username: onlyoffice
    #   existingSecret: ""
```

2. **Create init script ConfigMap**:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.postgres.fullname" . }}-init
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    
    {{- range $key, $db := .Values.postgres.databases }}
    {{- if $db.enabled }}
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE USER {{ $db.username }} WITH PASSWORD '${DB_PASS_{{ $key | upper }}}';
        CREATE DATABASE {{ $db.database }} OWNER {{ $db.username }};
        GRANT ALL PRIVILEGES ON DATABASE {{ $db.database }} TO {{ $db.username }};
    EOSQL
    {{- end }}
    {{- end }}
```

3. **Add init container to PostgreSQL deployment**
4. **Update service deployments** to use their specific database credentials

## Benefits

1. **Scalability**: Easy to add new services with database requirements
2. **Security**: Service isolation with dedicated credentials
3. **Maintainability**: Centralized database configuration
4. **Automation**: No manual database creation needed
5. **Best Practices**: Follows principle of least privilege

## Migration Path

1. **Backward Compatible**: Keep existing single database as default
2. **Opt-in**: Services can migrate to multi-database when ready
3. **Documentation**: Clear migration guide for users

## Testing Requirements

1. **Fresh Install**: Verify all databases are created correctly
2. **Upgrade Path**: Test migration from single to multi-database
3. **Service Connectivity**: Ensure each service connects to its database
4. **Secret Management**: Test with both inline passwords and existingSecrets

## References

- Discussed in PR #63: Database architecture limitations
- Related to Issue #93: PostgreSQL StatefulSet conversion
- PostgreSQL init scripts: https://github.com/docker-library/docs/blob/master/postgres/README.md#initialization-scripts

## Dependencies

- Should be implemented after Issue #93 (StatefulSet conversion) for better stability
- Coordinates with PR #63 (secret management) for credential handling
